### ISSUE TITLE
Name of the font and colorscheme 

### ISSUE THREAD

**Issue by ivanesmantovich** [eerohele/Tutkain#104]
Can you please tell me the name of the font and colorscheme used in the [docs](https://tutkain.flowthing.me/screenshots/basic-light.png)?
Thanks  @eerohele!!!

P.S Sorry if i am asking this question the wrong way, i couldn't find your e-mail

**Comment by eerohele** [comment]
Here's fine, I'm not exactly drawing in issues. :)

The font is [Iosevka](https://typeof.net/Iosevka/) (I don't remember the exact variant) and the color scheme is a customized (via the **UI: Customize Color Scheme** Sublime Text command) version of Sanakan, which ships as a part of [the Nil theme](https://github.com/nilium/st2-nil-theme).
