### ISSUE TITLE
`tutkain_goto_symbol_definition` doesn't move cursor if the definition is already in the scroll view

### ISSUE THREAD

**Issue by matusfi** [eerohele/Tutkain#29]
When I invoke `tutkain_goto_symbol_definition` on a var that is defined within the scrolled in view, the cursor doesn't jump.

My setup:
- Sublime Text Build 4087
- Tutkain 0.5.4
- Clojure 1.10.0
- nREPL 0.8.2

**Comment by matusfi** [comment]
Hi @eerohele ! Firstly, thank you for your work on Tutkain. I have been wishing for a Sublime plugin for Clojure that is usable, and look!-- my wish has come true 😄 I've been test driving it for a while and I really like it.

I'll try to improve this behaviour I mentioned, and hopefully I'll open a PR if you don't mind.

**Comment by eerohele** [comment]
> I've been test driving it for a while and I really like it.

Very glad to hear it! And thanks for filing the issue. :bow:

>I'll try to improve this behaviour I mentioned, and hopefully I'll open a PR if you don't mind.

A PR would be great! 👍

**Comment by eerohele** [comment]
I looked into this a bit and I don't really know why it happens. It *seems* like an issue in ST itself, but when I try it in safe mode, everything seems to work OK. Needs a bit more digging.

**Comment by matusfi** [comment]
I did look into it too. Same conclusion. I think it's related to the asynchronous nature of the `lookup` function, that in turn calls the `info.goto()` function as a callback. Maybe ST doesn't get the trigger to re-draw the view in this case, because calling `view.show()` doesn't need to move the viewport. However, when you swap it with `view.show_at_center()` it works nicely, except in case the destination line is already in the center of the viewport.

**Comment by eerohele** [comment]
This should work better in v0.7.0, which should appear in Package Control in a couple of hours, hopefully. If not, please open a new issue.
