### ISSUE TITLE
Unable to inline eval fractions

### ISSUE THREAD

**Issue by slifin** [eerohele/Tutkain#30]
If I send the following expression things work as expected
```
(+ 1 1) => 2
```

If I try and send:
```
1/2
```
On it's own then there's no output

**Comment by eerohele** [comment]
Which command are you using to evaluate the fraction? Do you have `1/2` selected when you try evaluating it, or is your cursor next to it? If your cursor is next to it, then it's expected that it doesn't work.

I realize now that the **Tutkain :Evaluate Innermost/Outermost Form** commands might be badly named. They're more like "Evaluate Innermost/Outermost Sexp" if you have nothing selected. If you have something selected, then they evaluate the selection. It's kinda hard to come up with a good name for those commands, though...

If I need to evaluate something that's not surrounded by brackets, I usually select it first using **Tutkain: Expand Selection** and then evaluate it using **Tutkain: Evaluate Outermost Form**. Does that work for you?

**Comment by slifin** [comment]
ah I see yeah it does work if I select the ratio first, I was leaving my cursor on one of the characters then sending to repl

with the following config: 
```
"command": "tutkain_evaluate_form",
    "args": {"scope": "outermost", "inline_result": true},
    "context": [{"key": "selector", "operator": "equal", "operand": "source.clojure"}]
```

**Comment by eerohele** [comment]
Yeah, I believe Cursive works the same way (or did when I last used it).

It might make sense for Tutkain to evaluate the form under the cursor without the user having to select it when using `tutkain_evaluate_form` with `"scope": "innermost"`. I'll think about it.

**Comment by eerohele** [comment]
v0.7.0 (which should appear in Package Control in a matter of hours) adds support for evaluating the adjacent form. For example:

```
{
    "keys": ["ctrl+c", "ctrl+w"],
    "command": "tutkain_evaluate",
    "args": {"scope": "form", "inline_result": true}
},
```
