### ISSUE TITLE
Symbol regex

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#38]
It looks like the regex for identifying symbols doesn't accept a question mark '?'

If you select the symbol `odd`, it highlights all four symbols including `odd?`:

![Screen Shot 2021-05-21 at 10 09 03 AM](https://user-images.githubusercontent.com/585191/119076418-b85ec000-ba1c-11eb-8430-4cff8e040440.png)

If you select `odd?`, it doesn't highlight the other `odd?`:

![Screen Shot 2021-05-21 at 10 09 11 AM](https://user-images.githubusercontent.com/585191/119076421-b98fed00-ba1c-11eb-9c1c-c6408a38dbe7.png)

**Comment by eerohele** [comment]
Yeah, this is an unfortunate issue, but it's an issue with Sublime Text, not Tutkain:

https://github.com/sublimehq/sublime_text/issues/3352

I don't think there's a workaround, but I could be wrong.
