### ISSUE TITLE
REPL view setting `scroll past end`

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#41]
Do you think it's reasonable to have a setting for `scroll_past_end` for the REPL views?

**Comment by eerohele** [comment]
Yes, that's a good idea. 👍🏻

Fixed in 0e4fba0dbe06310444f543bc6f376fed326158b2.

`0.5` is probably a reasonable default, but users really ought to be able to override it. Not difficult technically -- the hard part is figuring out how to structure and name the settings...

**Comment by pedrorgirardi** [comment]
Thank you!

0.5 is a good default, yes.
