### ISSUE TITLE
`tutkain_expand_selection` gets confused with `@`

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#48]
Cursor position:
![Screen Shot 2021-05-29 at 7 25 50 AM](https://user-images.githubusercontent.com/585191/120052462-a64dd480-c04f-11eb-9c70-7621e46cb4c5.png)

Expand selection:
![Screen Shot 2021-05-29 at 7 26 00 AM](https://user-images.githubusercontent.com/585191/120052464-a8179800-c04f-11eb-88c2-f63fd1548c9e.png)

Expand one more time, and the selection gets confusing:
![Screen Shot 2021-05-29 at 7 26 10 AM](https://user-images.githubusercontent.com/585191/120052466-a8b02e80-c04f-11eb-93d6-9f492d630314.png)

Expand again, and it does the right thing:
![Screen Shot 2021-05-29 at 7 26 31 AM](https://user-images.githubusercontent.com/585191/120052469-aa79f200-c04f-11eb-8186-258d7eef87bc.png)

**Comment by eerohele** [comment]
Thanks for the report! Yeah, looks like it only happens if the cursor is initially between the `@` and the `s`.

**Comment by eerohele** [comment]
Fixed in `develop`.
