### ISSUE TITLE
Maybe don't switch to non-existing namespace

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#54]
Auto-switching of namespaces is great! But there's a case where it might surprise you - and not in a good way.

You don't put your dev stuff in the `user` namespace; you put everything in `dev` instead. You're ready to start working, so you fire up your REPL and connect Tutkain to it. You have a `(dev)` function in your `user` namespace to require and switch to `dev,` so you open the file and evaluate `(dev)`.

It's sunny outside, and it's a beautiful day, and Clojure rocks. But then, you open your `dev` namespace and try to evaluate things, and, oh no, it doesn't work. How can it be?

Well, you had the `dev` namespace open when you connected to your REPL, and Tutkain tried to be helpful and load it for you. But `dev` doesn't exist, so Tutkain creates it for you `(ns dev)`. The problem is, that's not your *real* `dev` namespace, it looks like it is, but it's really not.

We discussed a little about this, and we think that maybe Tutkain shouldn't do it, don't auto-switch if the namespace doesn't exist.

The tricky thing is: what happens if the user evaluates things from this namespace? What should Tutkain do?

**Comment by eerohele** [comment]
Yes, the current implementation probably tries to be a bit too clever. I'll have to think about this a bit.

**Comment by eerohele** [comment]
One thing where auto-creating the namespace if it doesn't exist is useful is when you're creating a new namespace. Not that it's a huge bother to manually evaluate the `ns` form after writing it, of course.

**Comment by eerohele** [comment]
Also:

1. Create new file.
2. Add `ns` form but don't evaluate it.
3. Add `(inc 1)` and eval it. Works.
4. Switch to another file or another app.
5. Switch back to the new file.
6. Try evaluating `(inc 1)`. You'll get `Unable to resolve symbol: inc in this context`.

That's a bit suprising.

**Comment by eerohele** [comment]
I believe 0.14.0 addresses this problem.
