### ISSUE TITLE
Settings for REPL view

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#63]
What do you think about exposing some settings, e.g.: `word_wrap` and `font_size` for the REPL view? 

It doesn't make sense to expose these,  but `word_wrap` and `font_size` could be optionally set by the user. What do you reckon?

<img width="669" alt="Screen Shot 2021-08-10 at 8 19 51 PM" src="https://user-images.githubusercontent.com/585191/128874931-18d3d832-304b-4c3f-b321-1fc7c512e483.png">

**Comment by eerohele** [comment]
I think it makes sense. Something like `(merge default-options user-options)`, maybe.

**Comment by pedrorgirardi** [comment]
Cool! Would you like a PR? 

We can discuss implementation details in the PR.

**Comment by eerohele** [comment]
PR very welcome!
