### ISSUE TITLE
AttributeError: module 'Tutkain.src.repl' has no attribute 'JSClient'

### ISSUE THREAD

**Issue by aurelienbottazini** [eerohele/Tutkain#69]
Hello and thanks for your amazing work

I got this error trying to connect to a cljs repl.

```
  File "/Users/auray/Library/Application Support/Sublime Text/Packages/Tutkain/package.py", line 528, in run
    client = repl.JSClient(source_root(), host, int(port), prompt)
AttributeError: module 'Tutkain.src.repl' has no attribute 'JSClient'
```

The repl is running (shadow-cljs) and tuktain detects the correct port automatically. It get suggested when i run the command. 

I remember being able to connect to a cljs repl previously.

**Comment by eerohele** [comment]
Thanks for the report! Does restarting Sublime Text help?

**Comment by aurelienbottazini** [comment]
Yes indeed it works now!

The socket repl port is not picked automatically anymore but i can evaluate things in the buffer and get results :)

Thanks for your help

**Comment by eerohele** [comment]
Glad to hear it works. My apologies for the error. While refactoring, I moved a couple of internal classes into a different file, and for some reason, ST doesn't seem to always pick up those changes when updating the plugin via Package Control: Upgrade Package. No idea why that is. Well, at least I learned something, I guess.

Tutkain should definitely still pick up the port from the file as before. With shadow-cljs, it looks for the port number in `.shadow-cljs/socket-repl.port` under the root directory of the Sublime Text project you currently have open. Can you double-check that that file exists under your project root directory?

**Comment by aurelienbottazini** [comment]
Sorry for the delay in the response.
I tried again today and it does work again. 
Probably a restart issue too :)

**Comment by eerohele** [comment]
All right, glad to hear it, although my hope is certainly that Tutkain doesn't need constant restarting to work. If the issue occurs again, I'd appreciate it if you could open another issue.
