### ISSUE TITLE
Test runner error `AttributeError: 'NoneType' object has no attribute 'begin'`

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#74]
Try running a test with caret inside an empty collection:

<img width="175" alt="Screen Shot 2021-10-04 at 5 02 16 PM" src="https://user-images.githubusercontent.com/585191/135832677-3387e788-f75a-44c5-a3a2-56c7150d3a36.png">
<img width="166" alt="Screen Shot 2021-10-04 at 5 02 11 PM" src="https://user-images.githubusercontent.com/585191/135832684-8b419730-43c1-48db-9936-050561c4812c.png">

Tutkain will fail with:

<img width="919" alt="Screen Shot 2021-10-04 at 5 03 33 PM" src="https://user-images.githubusercontent.com/585191/135832767-026a9e32-214d-4e2b-a785-a28042a98c22.png">

This is fine though:

<img width="162" alt="Screen Shot 2021-10-04 at 5 02 21 PM" src="https://user-images.githubusercontent.com/585191/135832808-604cbb47-8855-4255-870f-8d0733937faf.png">

**Comment by eerohele** [comment]
Fixed on `develop`.
