### ISSUE TITLE
Make it possible to disable the REPL view

### ISSUE THREAD

**Issue by eerohele** [eerohele/Tutkain#79]
To cater to folks who'd [rather have inline results only and who don't need nested REPLs](https://tonsky.me/blog/sublime-clojure/), it should be possible to disable the REPL view completely. Maybe? Look into it, at least. Whence stdout, though?

**Comment by pedrorgirardi** [comment]
Could another option be to use the _tap output panel_? I don't use inline results, but when working on a small screen, I wish there was a way to hide the REPL panel, and it seems that the _tap output panel_ behaves somewhat like this.

**Comment by eerohele** [comment]
Using a panel that you must manually toggle might work. 👍🏻 I would probably be inclined keep it separate from the tap panel, though.

**Comment by pedrorgirardi** [comment]
Yeah, true, it might be better to keep it separated.

This would be a nice feature :)

**Comment by eerohele** [comment]
Using a panel for REPL output covers this, I think.
