### ISSUE TITLE
Consider parameter to disable showing the REPL panel after running tests

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#84]
When running tests I tend to check the red/green indicators on the margin:

<img width="1818" alt="Screen Shot 2022-02-02 at 16 50 07" src="https://user-images.githubusercontent.com/585191/152226454-cb31aee3-1a52-4f3e-ba0f-2dee86cb6b90.png">

But Tutkain always toggles the REPL panel after running the tests, and it might cover the source and indicators:

<img width="1818" alt="Screen Shot 2022-02-02 at 16 50 04" src="https://user-images.githubusercontent.com/585191/152226445-450c0c18-3871-4e9b-abfc-d2790b747bd0.png">

**Comment by eerohele** [comment]
Tutkain no longer prints anything in the output view after a test run. Instead, it shows a message in the status bar.
