### ISSUE TITLE
Tweak `tutkain_expand_selection` within a map

### ISSUE THREAD

**Issue by pedrorgirardi** [eerohele/Tutkain#97]
When expanding a selection within a map, it would be helpful to expand the selection one key pair at a time. 

Currently, once you expand the selection for a key or value, the next expansion is expanded for the whole map.

**Current**

Expand once:
<img width="63" alt="Screen Shot 2022-04-18 at 15 20 56" src="https://user-images.githubusercontent.com/585191/163855212-2070e1a0-78fd-4571-906e-cc896ec4e424.png">

Expand twice:
<img width="60" alt="Screen Shot 2022-04-18 at 15 21 03" src="https://user-images.githubusercontent.com/585191/163855235-ee2c57b4-016b-4b70-b52a-e9f70fd8bafd.png">

Expand three-times:
<img width="64" alt="Screen Shot 2022-04-18 at 15 21 08" src="https://user-images.githubusercontent.com/585191/163855271-fab76a63-51d1-4ac5-82cf-957c6040c3be.png">

**Desired**

Expand once:
<img width="61" alt="Screen Shot 2022-04-18 at 15 23 47" src="https://user-images.githubusercontent.com/585191/163855517-5fd081e4-ee71-4c08-b654-c62c6832ac26.png">

Expand twice:

<img width="61" alt="Screen Shot 2022-04-18 at 15 22 37" src="https://user-images.githubusercontent.com/585191/163855574-cbbe3314-d85d-4fb7-a86f-571e6c13abf0.png">

Expand three-times:
<img width="63" alt="Screen Shot 2022-04-18 at 15 22 47" src="https://user-images.githubusercontent.com/585191/163857301-076aade1-a2bd-4a11-9d5e-b660fcfdb480.png">

Expand four-times:
<img width="69" alt="Screen Shot 2022-04-18 at 15 22 52" src="https://user-images.githubusercontent.com/585191/163857326-a437a6c3-7306-4ea8-b797-1b6d04e539fc.png">

**Comment by eerohele** [comment]
Implemented (kinda) in 0.16.0.
